server:
  port: 7070
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://azqdiazdaeiaqj:797f07541854726e59f839e2ec8233781aee74d6e929e2b5b99a34bdcd50edef@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d1uvvnlm23kn7r
    username: azqdiazdaeiaqj
    password: 797f07541854726e59f839e2ec8233781aee74d6e929e2b5b99a34bdcd50edef
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend